#!/bin/bash

timeout=35

check() {
  echo checking $1;
  if easycrypt -I .  -I ./rewinding  -I ./aux -I ./HC -timeout $timeout $1 2>/dev/null;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

# list of files to check

## Generic stuff
check OneToManyZK.ec
check Generic_KE.ec
check Iterated_Failure_better.ec
check While_Props_Better.ec
check Generic_Defs_thy.ec

## Hamilton-Blum protocol
check HC/Basics.ec
check HC/Completeness.ec
check HC/SpecialSoundness.ec
check HC/PoK_Soundness.ec
check HC/ZK.ec 


echo "DONE";
