#!/bin/bash

timeout=20

check() {
  echo checking $1;
  if easycrypt -I .  -I ./rewinding  -I ./misc -I ./misc/while_props -I ./generic_sigma_protocols -timeout $timeout $1;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

# list of files to check

check misc/while_props/GenericKE.ec
check misc/while_props/OneToManyZK.ec
check misc/while_props/WhileCycle.ec
check misc/while_props/WhileNoSuccess.ec


## Generic sigma protocol defs/results
check generic_sigma_protocols/GenericSigmaProtocol.ec
check generic_sigma_protocols/GenericCompleteness.ec
check generic_sigma_protocols/GenericSoundness.ec
check generic_sigma_protocols/GenericZeroKnowledge.ec
check generic_sigma_protocols/GenericExtractability.ec
check generic_sigma_protocols/GenericSpecialSoundness.ec


## instance of Fiat-Shamir protocol
check case_studies/FiatShamir/FS_Basics.ec
check case_studies/FiatShamir/FS_Completeness.ec
check case_studies/FiatShamir/FS_SpecialSoundness.ec
check case_studies/FiatShamir/FS_Extractability.ec
check case_studies/FiatShamir/FS_Soundness.ec
check case_studies/FiatShamir/FS_Sim1Property.ec
check case_studies/FiatShamir/FS_ZeroKnowledge.ec


## instance of Schnorr protocol
check case_studies/Schnorr/Schnorr_Basics.ec
check case_studies/Schnorr/Schnorr_Completeness.ec
check case_studies/Schnorr/Schnorr_SpecialSoundness.ec
check case_studies/Schnorr/Schnorr_Extractability.ec

## instance of Blum protocol
check case_studies/HamiltonBlum/Blum_Basics.ec
check case_studies/HamiltonBlum/Blum_Completeness.ec
check case_studies/HamiltonBlum/Blum_SpecialSoundness.ec
check case_studies/HamiltonBlum/Blum_Extractability.ec
check case_studies/HamiltonBlum/Blum_Soundness.ec
check case_studies/HamiltonBlum/Blum_Sim1Property.ec
check case_studies/HamiltonBlum/Blum_ZeroKnowledge.ec


echo "DONE";
