#!/bin/bash

timeout=35

check() {
  echo checking $1;
  if easycrypt -I . -I ./QR -I ./rewinding -timeout $timeout $1 2>/dev/null;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

# list of files to check
check Iterated_Failure.ec
check while_not_b.ec
check while_not_b_proc.ec
check While_Props.ec
check QR/QR_Basics.ec
check QR/QR_Iterated_Soundness_Completeness.ec
check QR/QR_Iterated_ZK.ec

echo "DONE";
